site_name: FreeFlarum Documentation
site_url: https://www.freeflarum.com/docs/

theme:
   name: 'material'
   #  custom_dir: theme

# -----------------------------------------------
# need to enumerate everything, see this issue:
# https://github.com/mkdocs/mkdocs/issues/714
# -----------------------------------------------
nav:
  - Home: 'https://www.freeflarum.com/docs/'
  - About: 'about.md'
  - FaQ: 'faq.md'
  - Troubleshooting: 'troubleshooting.md'
  - Roadmap: 'roadmap.md'
  - Getting Started:
    - Basics:
        - 'Creating an Account': 'how-to/basics/creating-an-account.md'
        - 'Personalization': 'how-to/basics/personalization.md'
        - 'Private Forum': 'how-to/basics/private-forum.md'
  - Extensions:
    - 'What are Extensions?': 'how-to/extensions/about-extensions.md'
    - Extension List:
        - 'Analytics': 'how-to/extensions/analytics.md'
        - 'Approval': 'how-to/extensions/approval.md'
        - 'Arabic Language': 'how-to/extensions/arabic-language.md'
        - 'BBCode': 'how-to/extensions/bbcode.md'
        - 'Bosnian Language': 'how-to/extensions/bosanski.md'
        - 'Bosnian Language (Extended)': 'how-to/extensions/bosnian-extended-pack.md'
        - 'Brazilian Portuguese Language': 'how-to/extensions/brazilian-portuguese.md'
        - 'Canonical URL': 'how-to/extensions/canonical-url.md'
        - 'Deutsch Language': 'how-to/extensions/deutsch.md'
        - 'Discussion Views': 'how-to/extensions/discussion-views.md'
        - 'Dutch Language': 'how-to/extensions/dutch.md'
        - 'Embed': 'how-to/extensions/embed.md'
        - 'Emoji': 'how-to/extensions/emoji.md'
        - 'English': 'how-to/extensions/english.md'
        - 'Facebook Login': 'how-to/extensions/facebook-login.md'
        - 'Sitemap': 'how-to/extensions/flagrow-sitemap.md'
        - 'Flags': 'how-to/extensions/flags.md'
        - 'BBCode Details': 'how-to/extensions/fof-bbcode-details.md'
        - 'Ban IPs': 'how-to/extensions/fof-ban-ips.md'
        - 'Private Discussions (Byōbu)': 'how-to/extensions/fof-byobu.md'
        - 'Default Group': 'how-to/extensions/fof-default-group.md'
        - 'Default User Preferences': 'how-to/extensions/fof-default-user-preferences.md'
        - 'Discord Login': 'how-to/extensions/fof-discord-login.md'
  - Third-party Integrations:
    - Analytics:
        - 'Google Analytics': 'how-to/integrations/google-analytics.md'
    - Logins: 'how-to/integrations/logins.md'
        - 'Log In with Google': 'how-to/integrations/google-login.md'
        - 'Log In with Facebook': 'how-to/integrations/facebook-login.md'
        - 'Log In with GitHub': 'how-to/integrations/github-login.md'
        - 'Log In with Discord': 'how-to/integrations/discord-login.md'
        - 'Log In with Laravel': 'how-to/integrations/laravel-passport.md'
  - Advanced Usage:
    - 'Exporting Your Forum': 'how-to/advanced-setup/exporting-forum.md'
    - 'Custom Domain': 'how-to/advanced-setup/custom-domain.md'
    - 'Configuring Mail': 'how-to/advanced-setup/configuring-mail.md'
  - Legal:
    - 'Privacy Policy': 'legal/privacy-policy.md'
    - 'Terms': 'legal/terms.md'

extra_css:
  - 'style-tweaks/font-size.css'

markdown_extensions:
  - admonition
  
repo_url: https://github.com/gwillem/freeflarum.com
# edit_uri is not required for github
