site_name: FreeFlarum Documentation
site_url: https://www.freeflarum.com/docs/

theme:
   name: 'material'
   #  custom_dir: theme

# need to enumerate everything, see this issue:
# https://github.com/mkdocs/mkdocs/issues/714
nav:
  - Home: 'https://www.freeflarum.com/docs/'
  - About: about.md
  - FAQ: faq.md
  - Roadmap: roadmap.md
  - Getting Started:
    - howto/create-account.md
    - howto/personalize.md
    - howto/private-forum.md
  - Extensions:
    - howto/extensions/about-extensions.md
    - Extension List:
        - howto/extensions/Analytics.md
        - howto/extensions/Approval.md
        - howto/extensions/Arabic-language.md
        - howto/extensions/BBCode.md
        - howto/extensions/Bosanski.md
        - howto/extensions/Bosnian-Extended-Pack.md
  - Third-party integrations:
    - Analytics:
        - howto/google-analytics.md
    - Social logins:
        - howto/social-login/google.md
        - howto/social-login/facebook.md
        - howto/social-login/github.md
        - howto/social-login/passport.md
  - Advanced:
    - howto/export.md
    - howto/custom-domain.md
    - howto/configure-mail.md
  - Legal:
    - legal/privacy.md
    - legal/terms.md

markdown_extensions:
  - admonition
  
repo_url: https://github.com/gwillem/freeflarum.com
# edit_uri not required for github
